import * as Yup from 'yup';

export const configInitialValues = {
  propertyTitle: '',
  propertyDescription: '',
  propertyPrice: '',
  neighborhood: '',
  country: '',
  state: '',
  city: '',
  zipCode: '',
  address: '',
  propertyType: '',
  propertyStatus: '',
  area: '',
  rooms: '',
  bedrooms: '',
  bathrooms: '',
  garages: '',
  ammenities: [
    { label: 'Air Conditioned', value: false },
    { label: 'Basketball Court', value: false },
    { label: 'Balcony', value: false },
    { label: 'Beach ', value: false },
    { label: 'Coffee Pot', value: false },
    { label: 'Gym ', value: false },
    { label: 'Garage', value: false },
    { label: 'Heating ', value: false },
    { label: 'Internet ', value: false },
    { label: 'Laundry ', value: false },
    { label: 'Microwave ', value: false },
    { label: 'Roof terrace', value: false },
    { label: 'Smoking Allowed', value: false },
    { label: 'Swimming Pool', value: false },
    { label: 'Terrace', value: false },
    { label: 'Wheelchair Friendly', value: false }],
  gallery: []
}
export const propertySchema = Yup.object().shape({
  propertyTitle: Yup.string().required('This Field is required'),
  propertyDescription: Yup.string().required('This Field is required'),
  propertyPrice: Yup.string().required('This Field is required'),
  neighborhood: Yup.string().required('This Field is required'),
  country: Yup.string().required('This Field is required'),
  state: Yup.string().required('This Field is required'),
  city: Yup.string().required('This Field is required'),
  zipCode: Yup.string().required('This Field is required'),
  address: Yup.string().required('This Field is required'),
  propertyType: Yup.string().min(4, 'This Field is required').required('This Field is required'),
  propertyStatus: Yup.string().min(4, 'This Field is required').required('This Field is required'),
  area: Yup.string().required('This Field is required'),
  rooms: Yup.string().required('This Field is required'),
  bedrooms: Yup.string().required('This Field is required'),
  bathrooms: Yup.string().required('This Field is required'),
  garages: Yup.string().required('This Field is required'),
})